<?php

/**
 * This class is generated by makeActionForm tool.
 * @auchor makeActionForm
 */
use XCore\Form\ActionForm;
use XCore\Form\FieldProperty;
use XCore\Property\BoolArrayProperty;
use XCore\Property\BoolProperty;
use XCore\Property\IntArrayProperty;

class Xcore_CommentListForm extends ActionForm
{
	/**
	 * If the request is GET, never return token name.
	 * By this logic, a action can have three page in one action.
	 */
	function getTokenName()
	{
		//
		//
		if (xoops_getenv('REQUEST_METHOD') == 'POST') {
			return "module.xcore.CommentSettingsForm.TOKEN";
		}
		else {
			return null;
		}
	}
	
	/**
	 * For displaying the confirm-page, don't show CSRF error.
	 * Always return null.
	 */
	function getTokenErrorMessage()
	{
		return null;
	}
	
	function prepare()
	{
		// set properties
		$this->mFormProperties['status'] =new IntArrayProperty('status');
		$this->mFormProperties['delete']= new BoolArrayProperty('delete');
		//to display error-msg at confirm-page
		$this->mFormProperties['confirm'] =new BoolProperty('confirm');

		// set fields
		$this->mFieldProperties['status'] =new FieldProperty($this);
		$this->mFieldProperties['status']->setDependsByArray(array('required','objectExist'));
		$this->mFieldProperties['status']->addMessage('required', _MD_XCORE_ERROR_REQUIRED, _AD_XCORE_LANG_COM_STATUS);
		$this->mFieldProperties['status']->addMessage('objectExist', _AD_XCORE_ERROR_OBJECTEXIST, _AD_XCORE_LANG_COM_STATUS);
		$this->mFieldProperties['status']->addVar('handler', 'commentstatus');
		$this->mFieldProperties['status']->addVar('module', 'xcore');

	}
}

