<?php

/**
 * This class is generated by makeActionForm tool.
 * @auchor makeActionForm
 */
use XCore\Form\ActionForm;
use XCore\Form\FieldProperty;
use XCore\Property\BoolArrayProperty;
use XCore\Property\BoolProperty;
use XCore\Property\IntArrayProperty;
use XCore\Property\StringArrayProperty;

class Xcore_ImagecategoryListForm extends ActionForm
{
	/**
	 * If the request is GET, never return token name.
	 * By this logic, a action can have three page in one action.
	 */
	function getTokenName()
	{
		//
		//
		if (xoops_getenv('REQUEST_METHOD') == 'POST') {
			return "module.xcore.ImagecategorySettingsForm.TOKEN";
		}
		else {
			return null;
		}
	}
	
	/**
	 * For displaying the confirm-page, don't show CSRF error.
	 * Always return null.
	 */
	function getTokenErrorMessage()
	{
		return null;
	}
	
	function prepare()
	{
		// set properties
		$this->mFormProperties['name'] =new StringArrayProperty('name');
		$this->mFormProperties['maxsize'] =new IntArrayProperty('maxsize');
		$this->mFormProperties['maxwidth'] =new IntArrayProperty('maxwidth');
		$this->mFormProperties['maxheight'] =new IntArrayProperty('maxheight');
		$this->mFormProperties['display'] =new BoolArrayProperty('display');
		$this->mFormProperties['weight'] =new IntArrayProperty('weight');
		$this->mFormProperties['delete']=new BoolArrayProperty('delete');
		//to display error-msg at confirm-page
		$this->mFormProperties['confirm'] =new BoolProperty('confirm');
		// set fields
		$this->mFieldProperties['name'] =new FieldProperty($this);
		$this->mFieldProperties['name']->setDependsByArray(array('required','maxlength'));
		$this->mFieldProperties['name']->addMessage('required', _MD_XCORE_ERROR_REQUIRED, _AD_XCORE_LANG_IMGCAT_NAME, '100');
		$this->mFieldProperties['name']->addMessage('maxlength', _MD_XCORE_ERROR_MAXLENGTH, _AD_XCORE_LANG_IMGCAT_NAME, '100');
		$this->mFieldProperties['name']->addVar('maxlength', '100');
	
		$this->mFieldProperties['maxsize'] =new FieldProperty($this);
		$this->mFieldProperties['maxsize']->setDependsByArray(array('required'));
		$this->mFieldProperties['maxsize']->addMessage('required', _MD_XCORE_ERROR_REQUIRED, _AD_XCORE_LANG_IMGCAT_MAXSIZE);
	
		$this->mFieldProperties['maxwidth'] =new FieldProperty($this);
		$this->mFieldProperties['maxwidth']->setDependsByArray(array('required'));
		$this->mFieldProperties['maxwidth']->addMessage('required', _MD_XCORE_ERROR_REQUIRED, _AD_XCORE_LANG_IMGCAT_MAXWIDTH);
	
		$this->mFieldProperties['maxheight'] =new FieldProperty($this);
		$this->mFieldProperties['maxheight']->setDependsByArray(array('required'));
		$this->mFieldProperties['maxheight']->addMessage('required', _MD_XCORE_ERROR_REQUIRED, _AD_XCORE_LANG_IMGCAT_MAXHEIGHT);
	
		$this->mFieldProperties['weight'] =new FieldProperty($this);
		$this->mFieldProperties['weight']->setDependsByArray(array('required'));
		$this->mFieldProperties['weight']->addMessage('required', _MD_XCORE_ERROR_REQUIRED, _AD_XCORE_LANG_IMGCAT_WEIGHT);

	}
}

