<?php

/**
 * This class is generated by makeActionForm tool.
 * @auchor makeActionForm
 */
use XCore\Form\ActionForm;
use XCore\Form\FieldProperty;
use XCore\Property\BoolArrayProperty;
use XCore\Property\BoolProperty;
use XCore\Property\StringArrayProperty;

class Xcore_SmilesListForm extends ActionForm
{
	/**
	 * If the request is GET, never return token name.
	 * By this logic, a action can have three page in one action.
	 */
	function getTokenName()
	{
		//
		//
		if (xoops_getenv('REQUEST_METHOD') == 'POST') {
			return "module.xcore.SmilesSettingsForm.TOKEN";
		}
		else {
			return null;
		}
	}
	
	/**
	 * For displaying the confirm-page, don't show CSRF error.
	 * Always return null.
	 */
	function getTokenErrorMessage()
	{
		return null;
	}
	
	function prepare()
	{
		// set properties
		$this->mFormProperties['code']=new StringArrayProperty('code');
		$this->mFormProperties['emotion']=new StringArrayProperty('emotion');
		$this->mFormProperties['display']=new BoolArrayProperty('display');
		$this->mFormProperties['delete']=new BoolArrayProperty('delete');
		//to display error-msg at confirm-page
		$this->mFormProperties['confirm'] =new BoolProperty('confirm');
		// set fields
		$this->mFieldProperties['code']=new FieldProperty($this);
		$this->mFieldProperties['code']->setDependsByArray(array('required','maxlength'));
		$this->mFieldProperties['code']->addMessage("required",_MD_XCORE_ERROR_REQUIRED,_MD_XCORE_LANG_CODE,"50");
		$this->mFieldProperties['code']->addMessage("maxlength",_MD_XCORE_ERROR_MAXLENGTH,_MD_XCORE_LANG_CODE,"50");
		$this->mFieldProperties['code']->addVar("maxlength",50);

		$this->mFieldProperties['emotion']=new FieldProperty($this);
		$this->mFieldProperties['emotion']->setDependsByArray(array('required','maxlength'));
		$this->mFieldProperties['emotion']->addMessage("required",_MD_XCORE_ERROR_REQUIRED,_MD_XCORE_LANG_EMOTION,"75");
		$this->mFieldProperties['emotion']->addMessage("maxlength",_MD_XCORE_ERROR_MAXLENGTH,_MD_XCORE_LANG_EMOTION,"75");
		$this->mFieldProperties['emotion']->addVar("maxlength",75);

	}
}

