<?php

/***
 * @internal
 * This class is generated by makeActionForm tool.
 */
use XCore\Form\ActionForm;

class Xcore_TplsetDeleteForm extends ActionForm
{
	function getTokenName()
	{
		return "module.xcore.TplsetDeleteForm.TOKEN" . $this->get('tplset_id');
	}

	function prepare()
	{
		//
		// Set form properties
		//
		$this->mFormProperties['tplset_id'] =new XCube_IntProperty('tplset_id');

		//
		// Set field properties
		//
		$this->mFieldProperties['tplset_id'] =new XCube_FieldProperty($this);
		$this->mFieldProperties['tplset_id']->setDependsByArray(array('required'));
		$this->mFieldProperties['tplset_id']->addMessage('required', _AD_XCORE_ERROR_REQUIRED, _AD_XCORE_LANG_TPLSET_ID);
	}

	function load(&$obj)
	{
		$this->set('tplset_id', $obj->get('tplset_id'));
	}

	function update(&$obj)
	{
		$obj->set('tplset_id', $this->get('tplset_id'));
	}
}

