<?php

/**
 * This class is generated by makeActionForm tool.
 * @auchor makeActionForm
 */
use XCore\Form\ActionForm;
use XCore\Form\FieldProperty;

class User_UserListForm extends ActionForm
{
	/**
	 * If the request is GET, never return token name.
	 * By this logic, a action can have three page in one action.
	 */
	function getTokenName()
	{
		//
		//
		if (xoops_getenv('REQUEST_METHOD') == 'POST') {
			return "module.user.UserSettingsForm.TOKEN";
		}
		else {
			return null;
		}
	}
	
	/**
	 * For displaying the confirm-page, don't show CSRF error.
	 * Always return null.
	 */
	function getTokenErrorMessage()
	{
		return null;
	}
	
	function prepare()
	{
		// set properties
		$this->mFormProperties['level']= new XCube_IntArrayProperty('level');
		$this->mFormProperties['posts']= new XCube_IntArrayProperty('posts');
		$this->mFormProperties['delete']= new XCube_BoolArrayProperty('delete');
		//to display error-msg at confirm-page
		$this->mFormProperties['confirm'] =new XCube_BoolProperty('confirm');

		$this->mFieldProperties['level']= new FieldProperty($this);
		$this->mFieldProperties['level']->setDependsByArray(array('required','min'));
		$this->mFieldProperties['level']->addMessage('required', _MD_USER_ERROR_REQUIRED, _MD_USER_LANG_LEVEL);
		$this->mFieldProperties['level']->addMessage("min",_AD_USER_ERROR_MIN,_MD_USER_LANG_LEVEL,"0");
		$this->mFieldProperties['level']->addVar("min",0);

		$this->mFieldProperties['posts']= new FieldProperty($this);
		$this->mFieldProperties['posts']->setDependsByArray(array('required','min'));
		$this->mFieldProperties['posts']->addMessage('required', _MD_USER_ERROR_REQUIRED, _MD_USER_LANG_POSTS);
		$this->mFieldProperties['posts']->addMessage("min",_AD_USER_ERROR_MIN,_MD_USER_LANG_POSTS,"0");
		$this->mFieldProperties['posts']->addVar("min",0);

	}
}

?>
